### ISSUE TITLE
Move project to WebdriverIO Community Org

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-teamcity-reporter#25]
Hey @sullenor,

first off, thank you for creating this plugin and extending the WebdriverIO ecosystem!

We have been looking into successful WDIO plugins like this one as we want to ensure that its development can be continued even if the original maintainer decides to move on. Therefore on behalf of the WebdriverIO community I would like to ask if you would be interested to move this repository into the [WebdriverIO Community](https://github.com/webdriverio-community) organisation. It would allow us to help maintain this package, automate a few things like releases and allow others to contribute to it and make the package even better. You would of course continue to have full access to it.

What do you think? Please let me know if you have any questions.

**Comment by sullenor** [comment]
Hey @christian-bromann,

Thanks for reaching me out. Your proposal looks good for me, since I'm using the WebdriverIO ecosystem less these days and will be happy to see someone, who actively uses it, to maintain the plugin as well.

Do you have any guidance regarding how I can transfer the plugin to the community organisation? And do you use any specific test frameworks for the tools to make sure it is healthy?

**Comment by christian-bromann** [comment]
Hey! I am glad you accept the offer. I've invited you to the org which means that you can safely transfer the repository to it (a description on how to transfer repositories can be found in the [GithHub docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository)). In addition to that I would like to ask you if you could add [`wdio-user`](https://www.npmjs.com/~wdio-user) as NPM maintainer as we would like to setup automated release pipelines.

> And do you use any specific test frameworks for the tools to make sure it is healthy?

We have some monitoring systems, e.g. Orbit, in place to see how the community is growing. The most important reason is that the community is able to send bug fixes and do releases of these plugins.

**Comment by christian-bromann** [comment]
Thanks @sullenor

**Comment by sullenor** [comment]
@christian-bromann no problem, thank you for the guidance and let me know if you need more help!
