### ISSUE TITLE
Browser name is not included in results

### ISSUE THREAD

**Issue by donovan-shook** [webdriverio-community/wdio-teamcity-reporter#26]
I have added the following to my wdio config file...

`    
reporters: ['teamcity'],
    reporterOptions: {
        captureStandardOutput: true,
        flowId: true,
        message: '[browser]/[title]'
    }
`

However, the browser name is never added to the test results. I also tried updating some of the other options, such as the flowId and captureStandardOutput, but it looks like the defaults never change. I am using wdio-teamcity-reporter v3.0.0 and WDIO v.7

**Comment by christian-bromann** [comment]
Hi @donovan-shook ,
thanks for filing the issue. The docs were not up to date, the correct example looks as follows:

```js
exports.config = {
  // ...
  reporters: [
    [
      'teamcity',
      {
        captureStandardOutput: false, // optional
        flowId: true, // optional
        message: '[title]', // optional
      }
    ]
  ],
  // ...
}
```

Let me know if you have any further questions.

**Comment by sullenor** [comment]
@donovan-shook the way it is implemented — it picks `browserName` from capabilities section (code pointer https://github.com/webdriverio-community/wdio-teamcity-reporter/blob/main/index.js#L205). Can you please check that you have a `browserName` specified in your config? For example, it should work in the following way:

```
  capabilities: [
    {
      maxInstances: 2,
      browserName: 'chrome',
      'goog:chromeOptions': {
        args: ['headless', 'disable-gpu']
      }
    }
  ],
```
