### ISSUE TITLE
Change package name to common wdio naming convention

### ISSUE THREAD

**Issue by oshulimov-ontarget** [webdriverio-community/wdio-teamcity-reporter#29]
As a user, I would like to suggest to use same naming conventions as other webdriver-io packages since v6 to something like `@wdio/teamcity-reporter`

**Comment by christian-bromann** [comment]
@oshulimov-ontarget thanks for filing the issue. The `@wdio/teamcity-reporter` naming style is only for core packages. Given this is a community package and not part of the core repository we left it intentionally this way. Let me know if you have any further questions.
