### ISSUE TITLE
Update reporter to be compatible with WebdriverIO V8

### ISSUE THREAD

**Issue by kschiller** [webdriverio-community/wdio-teamcity-reporter#40]
Current version has dependencies fixed for WebdriverIO V7, so it won't install when using V8.
An update for V8 would be appreciated.

**Comment by christian-bromann** [comment]
Thanks for reporting the issue. Any contributions to make this happen would be appreciated.

**Comment by kschiller** [comment]
I am looking at this. It seems to be closely connected to #31, since the upgrade to wdio V8, as I understand it, requires the module to use ESM instead of CommonJS.

**Comment by christian-bromann** [comment]
@kschiller afaik CJS 3rd party plugins should also work with v8

**Comment by kschiller** [comment]
Yes, you are right. Only a small change is needed to resolve this issue. I will make a PR.
