### ISSUE TITLE
Tests fail locally and in CI

### ISSUE THREAD

**Issue by seanpoulter** [webdriverio-community/wdio-teamcity-reporter#54]
Hi folks, The tests in CI and locally. What's our strategy to maintain the repo and how can we help?

**Comment by christian-bromann** [comment]
The package hasn't been much maintained unfortunately. I've never used Teamcity myself so never needed to use the package. Some things that come to mind are:

- rewrite to TS
- transition to ESM, see #31
- add unit tests

**Comment by seanpoulter** [comment]
Thanks Christian. There's no `build` step right so we could even add TypeScript to check the existing JS.

**Comment by klamping** [comment]
Fixed with #60

**Comment by christian-bromann** [comment]
Thanks Kevin for taking a stab at this!
